### ISSUE TITLE
Please add these cheats for NFS Carbon OTC (ULES-00577)

### ISSUE THREAD

**Issue by MiguelCardonaG** [Saramagrean/CWCheat-Database-Plus-#13]
PPSSPP only:

_S ULES-00577
_G NEED FOR SPEED Carbon OTC (cheats by GameShark)
_C0 ACCEL YOUR CARS
_L 0x003E4F2A 0x0000008C
_L 0x003E4F2B 0x0000003D
_C0 BACKGROUND
_L 0x003E661F 0x0000003E
_C0 LIGHT
_L 0x003E980A 0x000000FF
_L 0x003E9A0A 0x00000040
_L 0x003E9A0B 0x00000043
_C0 HEADLIGHTS
_L 0x003E9687 0x00000043
_L 0x003E96C0 0x00000003
_L 0x003E96C4 0x00000000
_C0 ACCEL OPPONENTS
_L 0x003E4EF6 0x00000000
_L 0x003E4F02 0x00000000
_L 0x003E4F12 0x00000020
_L 0x003E4EFE 0x00000000
_C0 STEERING
_L 0x003EF4AB 0x00000044
_L 0x003EF49B 0x00000044
_L 0x003EF4B3 0x00000044
_L 0x003EF5C3 0x00000044
_L 0x003EF5D3 0x00000044
_L 0x003EF5DB 0x00000044
_C0 BACKLIGHTS
_L 0x003E982B 0x00000044
_L 0x003E9840 0x00000004

Thanks.

**Comment by Saramagrean** [comment]
Done.
