### ISSUE TITLE
[Bug] Invizimals cheats 

### ISSUE THREAD

**Issue by Dokman** [Saramagrean/CWCheat-Database-Plus-#2]
There are cheats of invizimals that aren't working like
I'm using TempAR 1.63 in a real PSP

- Infinite Health
- Infinite Stamina

**Comment by Saramagrean** [comment]
I look into soon.

**Comment by Dokman** [comment]
oh yes is in EUR version

**Comment by Dokman** [comment]
any updates @Saramagrean ?

**Comment by Dokman** [comment]
Closing as no words or pronunciation about this
