### ISSUE TITLE
tenchu san skin

### ISSUE THREAD

**Issue by IrfanH495** [Saramagrean/CWCheat-Database-Plus-#24]
did you copy the cheat from my video this one.
https://youtu.be/byYATKryYwA
better replace it with this one, at that time I was still very stupid when making cheats.
_C0 _______________[>>>Rikimaru Mission Codes<<<]_______________
_L 0x00000000 0x00000000
_C0 Stage 01 - Anjing [R]
_L 0x202638ED 0x0100002F
_C0 Stage 01 - Echigoya [R]
_L 0x202638ED 0x01000018
_C0 Stage 01 - Gadis [R]
_L 0x202638ED 0x01000045
_C0 Stage 01 - Kucing [R]
_L 0x202638ED 0x0100004A
_C0 Stage 01 - Nasu [R]
_L 0x202638ED 0x09000017
_C0 Stage 01 - Onikage [R]
_L 0x202638ED 0x00000010
_C0 Stage 01 - Ronin Bow [R]
_L 0x202638ED 0x18000020
_C0 Stage 01 - Ronin Spears [R]
_L 0x202638ED 0x11000020
_C0 Stage 01 - Ronin Sword [R]
_L 0x202638ED 0x01000020
_C0 Stage 01 - Samurai [R]
_L 0x202638ED 0x0100001D
_C0 Stage 01 - Semimaru [R]
_L 0x202638ED 0x00000047
_C0 Stage 01 - Tajima [R]
_L 0x202638ED 0x0E00001E
_C0 Stage 02 - Gohda Bow [R]
_L 0x202638ED 0x18000023
_C0 Stage 02 - Gohda Matsunoshin [R]
_L 0x202638ED 0x01000040
_C0 Stage 02 - Gohda Spears [R]
_L 0x202638ED 0x11000023
_C0 Stage 02 - Gohda Sword [R]
_L 0x202638ED 0x09000023
_C0 Stage 02 - Hamada [R]
_L 0x202638ED 0x01000019
_C0 Stage 02 - Ninja Claws [R]
_L 0x202638ED 0x13000024
_C0 Stage 02 - Ninja Sword [R]
_L 0x202638ED 0x01000024
_C0 Stage 02 - Sekia [R]
_L 0x202638ED 0x01000041
_C0 Stage 03 - Jonin Claws [R]
_L 0x202638ED 0x13000027
_C0 Stage 03 - Jonin Sword [R]
_L 0x202638ED 0x01000027
_C0 Stage 03 - Niken [R]
_L 0x202638ED 0x01000031
_C0 Stage 03 - Ninja Claws [R]
_L 0x202638ED 0x13000024
_C0 Stage 03 - Ninja Sword [R]
_L 0x202638ED 0x01000024
_C0 Stage 03 - Onikage [R]
_L 0x202638ED 0x01000011
_C0 Stage 03 - Onikage Black [R]
_L 0x202638ED 0x01000010
_C0 Stage 04 - Jonin Claws [R]
_L 0x202638ED 0x13000027
_C0 Stage 04 - Jonin Sword [R]
_L 0x202638ED 0x01000027
_C0 Stage 04 - Ninja Claws [R]
_L 0x202638ED 0x13000024
_C0 Stage 04 - Ninja Sword [R]
_L 0x202638ED 0x01000024
_C0 Stage 04 - Superior Kunoci [R]
_L 0x202638ED 0x14000034
_C0 Stage 05 - Anjing [R]
_L 0x202638ED 0x0100002F
_C0 Stage 05 - Chounin [R]
_L 0x202638ED 0x01000046
_C0 Stage 05 - Jinnai
_L 0x202638ED 0x01000014
_C0 Stage 05 - Ronin Bow [R]
_L 0x202638ED 0x18000020
_C0 Stage 05 - Ronin Spears [R]
_L 0x202638ED 0x11000020
_C0 Stage 05 - Ronin Sword [R]
_L 0x202638ED 0x01000020
_C0 Stage 05 - Samurai [R]
_L 0x202638ED 0x0100001D
_C0 Stage 06 - Karakuri Bows [R]
_L 0x202638ED 0x18000036
_C0 Stage 06 - Karakuri Samurai [R]
_L 0x202638ED 0x0100002B
_C0 Stage 06 - Karakuri Spears [R]
_L 0x202638ED 0x11000036
_C0 Stage 06 - Kiku Hime [R]
_L 0x202638ED 0x22000042
_C0 Stage 06 - Kimaira [R]
_L 0x202638ED 0x00000013
_C0 Stage 06 - Tenrai [R]
_L 0x202638ED 0x0800000C
_C0 Stage 07 - Kepala [R]
_L 0x202638ED 0x01000029
_C0 Stage 07 - Kucing [R]
_L 0x202638ED 0x1900004B
_C0 Stage 07 - Mayat Bow [R]
_L 0x202638ED 0x18000028
_C0 Stage 07 - Mayat Sword [R]
_L 0x202638ED 0x01000028
_C0 Stage 07 - Tatsumaru [R]
_L 0x202638ED 0x0F00000F
_C0 Stage 07 - Tenrai [R]
_L 0x202638ED 0x0800000C
_C0 Stage 07 - Tuyul [R]
_L 0x202638ED 0x0100002A
_C0 Stage 08 - Mifuyu Tadoroko [R]
_L 0x202638ED 0x22000066
_C0 Stage 08 - Prajurit Bow [R]
_L 0x202638ED 0x18000068
_C0 Stage 08 - Prajurit Spears [R]
_L 0x202638ED 0x11000068
_C0 Stage 08 - Prajurit Sword [R]
_L 0x202638ED 0x01000068
_C0 Stage 08 - Tadoroko [R]
_L 0x202638ED 0x0100006A
_C0 Stage 09 - Ayame [R]
_L 0x202638ED 0x14000007
_C0 Stage 09 - Ganda [R]
_L 0x002638ED 0x0A000012
_C0 Stage 09 - Jonin Claws [R]
_L 0x202638ED 0x13000027
_C0 Stage 09 - Jonin Sword [R]
_L 0x202638ED 0x01000027
_C0 Stage 09 - Kagura [R]
_L 0x202638ED 0x0D000015
_C0 Stage 09 - Serigala [R]
_L 0x202638ED 0x01000030
_C0 Stage 09 - Shikigami [R]
_L 0x202638ED 0x0000002C
_C0 Stage 09 - Tenrai [R]
_L 0x202638ED 0x0800010C
_C0 Stage 10 - Battle Priest Kenfo [R]
_L 0x202638ED 0x1600003B
_C0 Stage 10 - Beruang [R]
_L 0x002638ED 0x0000003A
_C0 Stage 10 - Ganda [R]
_L 0x002638ED 0x0A000012
_C0 Stage 10 - Kagura [R]
_L 0x202638ED 0x0D000015
_C0 Stage 10 - Komusou:Baskethead [R]
_L 0x202638ED 0x1500002E
_C0 Stage 10 - Tenrai [R]
_L 0x202638ED 0x08000000C
_C0 Stage 11 - Jonin Claws [R]
_L 0x202638ED 0x13000027
_C0 Stage 11 - Jonin Sword [R]
_L 0x202638ED 0x01000027
_C0 Stage 11 - Onikage [R]
_L 0x202638ED 0x01000011
_C0 Stage 11 - Superior Kunoci [R]
_L 0x202638ED 0x14000034
_C0 Stage 11 - Tenrai Priest
_L 0x202638ED 0x0000002D
_C0 Stage 12 - Jonin Claws [R]
_L 0x202638ED 0x13000027
_C0 Stage 12 - Jonin Sword [R]
_L 0x202638ED 0x01000027
_C0 Stage 12 - Superior Kunoci [R]
_L 0x202638ED 0x14000034
_C0 Stage 12 - Tenrai [R]
_L 0x202638ED 0x0800000C
_C0 Stage 12 - Tenrai Priest
_L 0x202638ED 0x0000002D
_C0 Stage 12 - Tenrai Snake [R]
_L 0x202638ED 0x0800000E
_C0 Stage 13 - MR.D [R]
_L 0x202638ED 0x2000001F
_C0 Stage 13 - Polisi Hitam [R]
_L 0x202638ED 0x2300003D
_C0 Stage 13 - Polisi Putih [R]
_L 0x202638ED 0x2100003E

**Comment by Saramagrean** [comment]
Done. :)
