### ISSUE TITLE
No cheats for Crisis Core: Final Fantasy VII

### ISSUE THREAD

**Issue by MiguelCardonaG** [Saramagrean/CWCheat-Database-Plus-#3]
Hello.

As the thread title says there are no cheats available for the game Crisis Core: Final Fantasy VII (ULES-01048) spanish version. Please add them.

![PPSSPP_2020-07-04-18-25-56](https://user-images.githubusercontent.com/65356692/86516804-d7179080-be23-11ea-9dee-bd3fbefa579f.jpg)

**Comment by MiguelCardonaG** [comment]
I just found these, you can add them?

_S ULES-01048
_G Final fantasy VII - Crisis core
_C0 Equipar 6 materias
_L 0x00223AD5 0x00000006
_C0 Magia al maximo
_L 0x00244E71 0x000000FF
_C0 Magia doble
_L 0x702451DE 0x00000040
_C1 Materias a MAESTRO
_L 0x0024363E 0x00000005
_C0 Todas las magias
_L 0x40243638 0x005B0003
_L 0x00014000 0x00000001
_L 0x4024363C 0x005B0003
_L 0xFF057005 0x00000001
_L 0x40243A7C 0x00120003
_L 0x0001407D 0x00000001
_L 0x20243A80 0xFF057069
_L 0x20243A8C 0xFF05706E
_L 0x40243A98 0x00070003
_L 0xFF05707D 0x00000005
_L 0x20243AEC 0xFF0570A5
_L 0x20243AF8 0xFF0570AA
_L 0x20243B04 0xFF0570A0
_L 0x20243B10 0xFF0570AF
_L 0x40243B1C 0x00030003
_L 0x0001407D 0x00000005
_L 0x20243B40 0xFF0570C8
_L 0x20243A8C 0xFF0570CD
_C0 Todos los accesorios
_L 0x40243258 0x006C0001
_L 0x00635000 0x00000001
_C0 Todos los estados positivos
_L 0x00245177 0x0000007F
_L 0x00245176 0x0000007F
_L 0x00245175 0x0000007F
_L 0x00245174 0x0000007F
_L 0x0024516F 0x0000007F
_L 0x00245170 0x0000007F
_L 0x00245173 0x0000007F
_L 0x00245171 0x0000007F
_L 0x00245178 0x0000007F
_L 0x00245179 0x0000007F
_C0 Todos los objetos
_L 0x40243238 0x00080001
_L 0x00632000 0x00000001
_L 0x40243258 0x006C0001
_L 0x00635000 0x00000001
_L 0x40243408 0x00180001
_L 0x00633000 0x00000001
_L 0x00633000 0x00000001
_C0 Vida al maximo
_L 0x20244E4C 0x0001869F
_C0 Vida infinita
_L 0x20244E48 0x0001869F
_C0 Ps infinitos
_L 0x20244E44 0x3B9AC9FF
_C0 Desbloquear toda la OMD
_L 0x40244F4C 0x00240002
_L 0x7FFFFFFF 0x00000000
_L 0x00244EB2 0x00000004
_L 0x40244F94 0x00030001
_L 0x00000007 0x00000000
_L 0x40243474 0x000B0001
_L 0x0001301B 0x00000001
_L 0x80223AD8 0x00070001
_L 0x00000001 0x00000000
_C0 Desbloquear todas las misiones
_L 0x80223260 0x012C0003
_L 0x00001981 0x00000000
_L 0x80223261 0x012C0003
_L 0x00001981 0x00000000
_C0 Desbloquear todas las tiendas
_L 0x402434A0 0x000F0001
_L 0x00013026 0x00000001
_C0 Max HP-MP-AP-SP
_L 0x20244E64 0x0001869F
_L 0x20244E60 0x0001869F
_L 0x20244E58 0x0001869F
_L 0x20244E54 0x0001869F
_L 0x20244E4C 0x0001869F
_L 0x20244E48 0x0001869F
_C0 Max FUE-ENT-MAG-INT-SUE
_L 0x00244E6F 0x000000FF
_L 0x00244E75 0x000000FF
_L 0x00244E70 0x000000FF
_L 0x00244E76 0x000000FF
_L 0x00244E71 0x000000FF
_L 0x00244E77 0x000000FF
_L 0x00244E72 0x000000FF
_L 0x00244E78 0x000000FF
_L 0x00244E73 0x000000FF
_L 0x00244E79 0x000000FF
_C0 Tener lvl-99
_L 0x00244E6E 0x00000063
_C0 Dinero Infinito
_L 0x20244EE8 0x05F5E0FF

**Comment by Dokman** [comment]
I'll tetst It tomorrow, i Will answer if works Well. thanks

**Comment by Saramagrean** [comment]
Okay.

**Comment by Saramagrean** [comment]
@MiguelCardonaG Done.

**Comment by MiguelCardonaG** [comment]
> @MiguelCardonaG Done.

Thank you.
