### ISSUE TITLE
PixelJunk Monsters Deluxe

### ISSUE THREAD

**Issue by illteteka** [Saramagrean/CWCheat-Database-Plus-#32]
I wrote a cheat code to enable a developer setting for infinite gems and money. Would be much appreciated if it could be added to the database!

    _S UCUS-98739
    _G PixelJunk Monsters Deluxe
    _C1 Infinite Gems and Coins
    _L 0x00D20BE1 0x3D3D3128
    _L 0x00D20BE5 0x2F2F2931

**Comment by Micsuit** [comment]
Make a pull request!

**Comment by Saramagrean** [comment]
Thanks, It's done.
