### ISSUE TITLE
Not an issue; addition. FFIV The After Years.  98 of everything

### ISSUE THREAD

**Issue by WolfWoman24** [Saramagrean/CWCheat-Database-Plus-#33]
I found it but I can't remember where so....awesome job if you come across this whom ever you are. I just added it to the end of ULUS1056.ini in  //psp/cheats  Your cheat.db was to big to edit on my g2 fire cube or I would have done it there. It only works for The After Years which is great because there's no fat chocobo. 

_C0 98x Everything
_L 0x0079425C 0x00000062
_L 0x0079425E 0x00000062
_L 0x00794260 0x00000062
_L 0x00794262 0x00000062
_L 0x00794264 0x00000062
_L 0x00794266 0x00000062
_L 0x00794268 0x00000062
_L 0x0079426A 0x00000062
_L 0x0079426C 0x00000062
_L 0x0079426E 0x00000062
_L 0x00794270 0x00000062
_L 0x00794272 0x00000062
_L 0x00794274 0x00000062
_L 0x00794276 0x00000062
_L 0x00794278 0x00000062
_L 0x0079427A 0x00000062
_L 0x0079427C 0x00000062
_L 0x0079427E 0x00000062
_L 0x00794280 0x00000062
_L 0x00794282 0x00000062
_L 0x00794284 0x00000062
_L 0x00794286 0x00000062
_L 0x00794288 0x00000062
_L 0x0079428A 0x00000062
_L 0x0079428C 0x00000062
_L 0x0079428E 0x00000062
_L 0x00794290 0x00000062
_L 0x00794292 0x00000062
_L 0x00794294 0x00000062
_L 0x00794296 0x00000062
_L 0x00794298 0x00000062
_L 0x0079429A 0x00000062
_L 0x0079429C 0x00000062
_L 0x0079429E 0x00000062
_L 0x007942A0 0x00000062
_L 0x007942A2 0x00000062
_L 0x007942A4 0x00000062
_L 0x007942A6 0x00000062
_L 0x007942A8 0x00000062
_L 0x007942AA 0x00000062
_L 0x007942AC 0x00000062
_L 0x007942AE 0x00000062
_L 0x007942B0 0x00000062
_L 0x007942B2 0x00000062
_L 0x007942B4 0x00000062
_L 0x007942B6 0x00000062
_L 0x007942B8 0x00000062
_L 0x007942BA 0x00000062
_L 0x007942BC 0x00000062
_L 0x007942BE 0x00000062
_L 0x007942C0 0x00000062
_L 0x007942C2 0x00000062
_L 0x007942C4 0x00000062
_L 0x007942C6 0x00000062
_L 0x007942C8 0x00000062
_L 0x007942CA 0x00000062
_L 0x007942CC 0x00000062
_L 0x007942CE 0x00000062
_L 0x007942D0 0x00000062
_L 0x007942D2 0x00000062
_L 0x007942D4 0x00000062
_L 0x007942D6 0x00000062
_L 0x007942D8 0x00000062
_L 0x007942DA 0x00000062
_L 0x007942DC 0x00000062
_L 0x007942DE 0x00000062
_L 0x007942E0 0x00000062
_L 0x007942E2 0x00000062
_L 0x007942E4 0x00000062
_L 0x007942E6 0x00000062
_L 0x007942E8 0x00000062
_L 0x007942EA 0x00000062
_L 0x007942EC 0x00000062
_L 0x007942EE 0x00000062
_L 0x007942F0 0x00000062
_L 0x007942F2 0x00000062
_L 0x007942F4 0x00000062
_L 0x007942F6 0x00000062
_L 0x007942F8 0x00000062
_L 0x007942FA 0x00000062
_L 0x007942FC 0x00000062
_L 0x007942FE 0x00000062
_L 0x00794300 0x00000062
_L 0x00794302 0x00000062
_L 0x00794304 0x00000062
_L 0x00794306 0x00000062
_L 0x00794308 0x00000062
_L 0x0079430A 0x00000062
_L 0x0079430C 0x00000062
_L 0x0079430E 0x00000062
_L 0x00794310 0x00000062
_L 0x00794312 0x00000062
_L 0x00794314 0x00000062
_L 0x00794316 0x00000062
_L 0x00794318 0x00000062
_L 0x0079431A 0x00000062
_L 0x0079431C 0x00000062
_L 0x0079431E 0x00000062
_L 0x00794320 0x00000062
_L 0x00794322 0x00000062
_L 0x00794324 0x00000062
_L 0x00794326 0x00000062
_L 0x00794328 0x00000062
_L 0x0079432A 0x00000062
_L 0x0079432C 0x00000062
_L 0x0079432E 0x00000062
_L 0x00794330 0x00000062
_L 0x00794332 0x00000062
_L 0x00794334 0x00000062
_L 0x00794336 0x00000062
_L 0x00794338 0x00000062
_L 0x0079433A 0x00000062
_L 0x0079433C 0x00000062
_L 0x0079433E 0x00000062
_L 0x00794340 0x00000062
_L 0x00794342 0x00000062
_L 0x00794344 0x00000062
_L 0x00794346 0x00000062
_L 0x00794348 0x00000062
_L 0x0079434A 0x00000062
_L 0x0079434C 0x00000062
_L 0x0079434E 0x00000062
_L 0x00794350 0x00000062
_L 0x00794352 0x00000062
_L 0x00794354 0x00000062
_L 0x00794356 0x00000062
_L 0x00794358 0x00000062
_L 0x0079435A 0x00000062
_L 0x0079435C 0x00000062
_L 0x0079435E 0x00000062
_L 0x00794360 0x00000062
_L 0x00794362 0x00000062
_L 0x00794364 0x00000062
_L 0x00794366 0x00000062
_L 0x00794368 0x00000062
_L 0x0079436A 0x00000062
_L 0x0079436C 0x00000062
_L 0x0079436E 0x00000062
_L 0x00794370 0x00000062
_L 0x00794372 0x00000062
_L 0x00794374 0x00000062
_L 0x00794376 0x00000062
_L 0x00794378 0x00000062
_L 0x0079437A 0x00000062
_L 0x0079437C 0x00000062
_L 0x0079437E 0x00000062
_L 0x00794380 0x00000062
_L 0x00794382 0x00000062
_L 0x00794384 0x00000062
_L 0x00794386 0x00000062
_L 0x00794388 0x00000062
_L 0x0079438A 0x00000062
_L 0x0079438C 0x00000062
_L 0x0079438E 0x00000062
_L 0x00794390 0x00000062
_L 0x00794392 0x00000062
_L 0x00794394 0x00000062
_L 0x00794396 0x00000062
_L 0x00794398 0x00000062
_L 0x0079439A 0x00000062
_L 0x0079439C 0x00000062
_L 0x0079439E 0x00000062
_L 0x007943A0 0x00000062
_L 0x007943A2 0x00000062
_L 0x007943A4 0x00000062
_L 0x007943A6 0x00000062
_L 0x007943A8 0x00000062
_L 0x007943AA 0x00000062
_L 0x007943AC 0x00000062
_L 0x007943AE 0x00000062
_L 0x007943B0 0x00000062
_L 0x007943B2 0x00000062
_L 0x007943B4 0x00000062
_L 0x007943B6 0x00000062
_L 0x007943B8 0x00000062
_L 0x007943BA 0x00000062
_L 0x007943BC 0x00000062
_L 0x007943BE 0x00000062
_L 0x007943C0 0x00000062
_L 0x007943C2 0x00000062
_L 0x007943C4 0x00000062
_L 0x007943C6 0x00000062
_L 0x007943C8 0x00000062
_L 0x007943CA 0x00000062
_L 0x007943CC 0x00000062
_L 0x007943CE 0x00000062
_L 0x007943D0 0x00000062
_L 0x007943D2 0x00000062
_L 0x007943D4 0x00000062
_L 0x007943D6 0x00000062
_L 0x007943D8 0x00000062
_L 0x007943DA 0x00000062
_L 0x007943DC 0x00000062
_L 0x007943DE 0x00000062
_L 0x007943E0 0x00000062
_L 0x007943E2 0x00000062
_L 0x007943E4 0x00000062
_L 0x007943E6 0x00000062
_L 0x007943E8 0x00000062
_L 0x007943EA 0x00000062
_L 0x007943EC 0x00000062
_L 0x007943EE 0x00000062
_L 0x007943F0 0x00000062
_L 0x007943F2 0x00000062
_L 0x007943F4 0x00000062
_L 0x007943F6 0x00000062
_L 0x007943F8 0x00000062
_L 0x007943FA 0x00000062
_L 0x007943FC 0x00000062
_L 0x007943FE 0x00000062
_L 0x00794400 0x00000062
_L 0x00794402 0x00000062
_L 0x00794404 0x00000062
_L 0x00794406 0x00000062
_L 0x00794408 0x00000062
_L 0x0079440A 0x00000062
_L 0x0079440C 0x00000062
_L 0x0079440E 0x00000062
_L 0x00794410 0x00000062
_L 0x00794412 0x00000062
_L 0x00794414 0x00000062
_L 0x00794416 0x00000062
_L 0x00794418 0x00000062
_L 0x0079441A 0x00000062
_L 0x0079441C 0x00000062
_L 0x0079441E 0x00000062
_L 0x00794420 0x00000062
_L 0x00794422 0x00000062
_L 0x00794424 0x00000062
_L 0x00794426 0x00000062
_L 0x00794428 0x00000062
_L 0x0079442A 0x00000062
_L 0x0079442C 0x00000062
_L 0x0079442E 0x00000062
_L 0x00794430 0x00000062
_L 0x00794432 0x00000062
_L 0x00794434 0x00000062
_L 0x00794436 0x00000062
_L 0x00794438 0x00000062
_L 0x0079443A 0x00000062
_L 0x0079443C 0x00000062
_L 0x0079443E 0x00000062
_L 0x00794440 0x00000062
_L 0x00794442 0x00000062
_L 0x00794444 0x00000062
_L 0x00794446 0x00000062
_L 0x00794448 0x00000062
_L 0x0079444A 0x00000062
_L 0x0079444C 0x00000062
_L 0x0079444E 0x00000062
_L 0x00794450 0x00000062
_L 0x00794452 0x00000062
_L 0x00794454 0x00000062
_L 0x00794456 0x00000062
_L 0x00794458 0x00000062
_L 0x0079445A 0x00000062
_L 0x0079445C 0x00000062
_L 0x0079445E 0x00000062
_L 0x00794460 0x00000062
_L 0x00794462 0x00000062
_L 0x00794464 0x00000062
_L 0x00794466 0x00000062
_L 0x00794468 0x00000062
_L 0x0079446A 0x00000062
_L 0x0079446C 0x00000062
_L 0x0079446E 0x00000062
_L 0x00794470 0x00000062
_L 0x00794472 0x00000062
_L 0x00794474 0x00000062
_L 0x00794476 0x00000062
_L 0x00794478 0x00000062
_L 0x0079447A 0x00000062
_L 0x0079447C 0x00000062
_L 0x0079447E 0x00000062
_L 0x00794480 0x00000062
_L 0x00794482 0x00000062
_L 0x00794484 0x00000062
_L 0x00794486 0x00000062
_L 0x00794488 0x00000062
_L 0x0079448A 0x00000062
_L 0x0079448C 0x00000062
_L 0x0079448E 0x00000062
_L 0x00794490 0x00000062
_L 0x00794492 0x00000062
_L 0x00794494 0x00000062
_L 0x00794496 0x00000062
_L 0x00794498 0x00000062
_L 0x0079449A 0x00000062
_L 0x0079449C 0x00000062
_L 0x0079449E 0x00000062
_L 0x007944A0 0x00000062
_L 0x007944A2 0x00000062
_L 0x007944A4 0x00000062
_L 0x007944A6 0x00000062
_L 0x007944A8 0x00000062
_L 0x007944AA 0x00000062
_L 0x007944AC 0x00000062
_L 0x007944AE 0x00000062
_L 0x007944B0 0x00000062
_L 0x007944B2 0x00000062
_L 0x007944B4 0x00000062
_L 0x007944B6 0x00000062
_L 0x007944B8 0x00000062
_L 0x007944BA 0x00000062
_L 0x007944BC 0x00000062
_L 0x007944BE 0x00000062
_L 0x007944C0 0x00000062
_L 0x007944C2 0x00000062
_L 0x007944C4 0x00000062
_L 0x007944C6 0x00000062
_L 0x007944C8 0x00000062
_L 0x007944CA 0x00000062
_L 0x007944CC 0x00000062
_L 0x007944CE 0x00000062
_L 0x007944D0 0x00000062
_L 0x007944D2 0x00000062
_L 0x007944D4 0x00000062
_L 0x007944D6 0x00000062
_L 0x007944D8 0x00000062
_L 0x007944DA 0x00000062
_L 0x007944DC 0x00000062
_L 0x007944DE 0x00000062
_L 0x007944E0 0x00000062
_L 0x007944E2 0x00000062
_L 0x007944E4 0x00000062
_L 0x007944E6 0x00000062
_L 0x007944E8 0x00000062
_L 0x007944EA 0x00000062
_L 0x007944EC 0x00000062
_L 0x007944EE 0x00000062
_L 0x007944F0 0x00000062
_L 0x007944F2 0x00000062
_L 0x007944F4 0x00000062
_L 0x007944F6 0x00000062
_L 0x007944F8 0x00000062
_L 0x007944FA 0x00000062
_L 0x007944FC 0x00000062
_L 0x007944FE 0x00000062
_L 0x00794500 0x00000062
_L 0x00794502 0x00000062
_L 0x00794504 0x00000062
_L 0x00794506 0x00000062
_L 0x00794508 0x00000062
_L 0x0079450A 0x00000062
_L 0x0079450C 0x00000062
_L 0x0079450E 0x00000062
_L 0x00794510 0x00000062
_L 0x00794512 0x00000062
_L 0x00794514 0x00000062
_L 0x00794516 0x00000062
_L 0x00794518 0x00000062
_L 0x0079451A 0x00000062
_L 0x0079451C 0x00000062
_L 0x0079451E 0x00000062
_L 0x00794520 0x00000062
_L 0x00794522 0x00000062
_L 0x00794524 0x00000062
_L 0x00794526 0x00000062
_L 0x00794528 0x00000062
_L 0x0079452A 0x00000062
_L 0x0079452C 0x00000062
_L 0x0079452E 0x00000062
_L 0x00794530 0x00000062
_L 0x00794532 0x00000062
_L 0x00794534 0x00000062
_L 0x00794536 0x00000062
_L 0x00794538 0x00000062
_L 0x0079453A 0x00000062
_L 0x0079453C 0x00000062
_L 0x0079453E 0x00000062
_L 0x00794540 0x00000062
_L 0x00794542 0x00000062
_L 0x00794544 0x00000062
_L 0x00794546 0x00000062
_L 0x00794548 0x00000062
_L 0x0079454A 0x00000062
_L 0x0079454C 0x00000062
_L 0x0079454E 0x00000062
_L 0x00794550 0x00000062
_L 0x00794552 0x00000062
_L 0x00794554 0x00000062
_L 0x00794556 0x00000062
_L 0x00794558 0x00000062
_L 0x0079455A 0x00000062
_L 0x0079455C 0x00000062
_L 0x0079455E 0x00000062
_L 0x00794560 0x00000062
_L 0x00794562 0x00000062
_L 0x00794564 0x00000062
_L 0x00794566 0x00000062
_L 0x00794568 0x00000062
_L 0x0079456A 0x00000062
_L 0x0079456C 0x00000062
_L 0x0079456E 0x00000062
_L 0x00794570 0x00000062
_L 0x00794572 0x00000062
_L 0x00794574 0x00000062
_L 0x00794576 0x00000062
_L 0x00794578 0x00000062
_L 0x0079457A 0x00000062
_L 0x0079457C 0x00000062
_L 0x0079457E 0x00000062
_L 0x00794580 0x00000062
_L 0x00794582 0x00000062
_L 0x00794584 0x00000062
_L 0x00794586 0x00000062
_L 0x00794588 0x00000062
_L 0x0079458A 0x00000062
_L 0x0079458C 0x00000062
_L 0x0079458E 0x00000062
_L 0x00794590 0x00000062
_L 0x00794592 0x00000062
_L 0x00794594 0x00000062
_L 0x00794596 0x00000062
_L 0x00794598 0x00000062
_L 0x0079459A 0x00000062
_L 0x0079459C 0x00000062
_L 0x0079459E 0x00000062
_L 0x007945A0 0x00000062
_L 0x007945A2 0x00000062
_L 0x007945A4 0x00000062
_L 0x007945A6 0x00000062
_L 0x007945A8 0x00000062
_L 0x007945AA 0x00000062
_L 0x007945AC 0x00000062
_L 0x007945AE 0x00000062
_L 0x007945B0 0x00000062
_L 0x007945B2 0x00000062
_L 0x007945B4 0x00000062
_L 0x007945B6 0x00000062
_L 0x007945B8 0x00000062
_L 0x007945BA 0x00000062
_L 0x007945BC 0x00000062
_L 0x007945BE 0x00000062
_L 0x007945C0 0x00000062
_L 0x007945C2 0x00000062
_L 0x007945C4 0x00000062
_L 0x007945C6 0x00000062
_L 0x007945C8 0x00000062
_L 0x007945CA 0x00000062
_L 0x007945CC 0x00000062
_L 0x007945CE 0x00000062
_L 0x007945D0 0x00000062
_L 0x007945D2 0x00000062
_L 0x007945D4 0x00000062
_L 0x007945D6 0x00000062
_L 0x007945D8 0x00000062
_L 0x007945DA 0x00000062
_L 0x007945DC 0x00000062
_L 0x007945DE 0x00000062
_L 0x007945E0 0x00000062
_L 0x007945E2 0x00000062
_L 0x007945E4 0x00000062
_L 0x007945E6 0x00000062
_L 0x007945E8 0x00000062
_L 0x007945EA 0x00000062
_L 0x007945EC 0x00000062
_L 0x007945EE 0x00000062
_L 0x007945F0 0x00000062
_L 0x007945F2 0x00000062
_L 0x007945F4 0x00000062
_L 0x007945F6 0x00000062
_L 0x007945F8 0x00000062
_L 0x007945FA 0x00000062
_L 0x007945FC 0x00000062
_L 0x007945FE 0x00000062
_L 0x00794600 0x00000062
_L 0x00794602 0x00000062
_L 0x00794604 0x00000062
_L 0x00794606 0x00000062
_L 0x00794608 0x00000062
_L 0x0079460A 0x00000062
_L 0x0079460C 0x00000062
_L 0x0079460E 0x00000062
_L 0x00794610 0x00000062
_L 0x00794612 0x00000062
_L 0x00794614 0x00000062
_L 0x00794616 0x00000062
_L 0x00794618 0x00000062
_L 0x0079461A 0x00000062
_L 0x0079461C 0x00000062
_L 0x0079461E 0x00000062
_L 0x00794620 0x00000062
_L 0x00794622 0x00000062
_L 0x00794624 0x00000062
_L 0x00794626 0x00000062
_L 0x00794628 0x00000062
_L 0x0079462A 0x00000062
_L 0x0079462C 0x00000062
_L 0x0079462E 0x00000062
_L 0x00794630 0x00000062
_L 0x00794632 0x00000062
_L 0x00794634 0x00000062
_L 0x00794636 0x00000062
_L 0x00794638 0x00000062
_L 0x0079463A 0x00000062
_L 0x0079463C 0x00000062
_L 0x0079463E 0x00000062
_L 0x00794640 0x00000062
_L 0x00794642 0x00000062
_L 0x00794644 0x00000062
_L 0x00794646 0x00000062

**Comment by Saramagrean** [comment]
Sure.

**Comment by Saramagrean** [comment]
Done.
