### ISSUE TITLE
World Tour Soccer - Challenge Mode - Pass to add 500

### ISSUE THREAD

**Issue by sebastienrougetenercoop** [Saramagrean/CWCheat-Database-Plus-#34]
Tested on PSP-E1004, under 6.61 PRO-C3 ∞, with TempAR 1.64.

In Challenge Mode, it will add 500 points to your score each time you pass the ball, until you reach 5000 points. The maximum score before it starts to glitch is ~6300 points. It is safe to use on each challenge, and clearly enough to beat each one.

```
_S UCES-00003
_G World Tour Soccer
_C0 Challenge - Pass to add 500
_L 0xE0011388 0x090E29D0
_L 0xD0000000 0x00008000
_L 0x303001F4 0x090E29D0
```

**Comment by Saramagrean** [comment]
Okay.
