### ISSUE TITLE
Fix for ULES-00176: Tales Of Eternia [EU]

### ISSUE THREAD

**Issue by eku** [Saramagrean/CWCheat-Database-Plus-#47]
The cheat code for `Disable Random Battles` freezes the game.

According to the [thread](https://gamefaqs.gamespot.com/boards/920817-tales-of-eternia/78874265) the address is `0x10D68C22` and not `0x20D68C22`, as in your db file. I can confirm that `0x10D68C22` works.

**Comment by Saramagrean** [comment]
Oke.

**Comment by eku** [comment]
> Oke.

Do you want me to provide a PR?

**Comment by Saramagrean** [comment]
I will update soon. thanks!
