### ISSUE TITLE
What license does this project have?

### ISSUE THREAD

**Issue by jserodio** [Saramagrean/CWCheat-Database-Plus-#7]
We're interested in including these cheats on a project called 351elec, it's an OS build by the community for the Anbernic's RG351P and RG351M console.
But we need to know if the current license on this cheats.db file, will allow us to include and ship it with it.
Best regards,

**Comment by jserodio** [comment]
Can we upload this file to our project?

**Comment by Saramagrean** [comment]
Sure.

**Comment by jserodio** [comment]
Cool thanks!
